import { Language } from "./types";

export const APP_NAME = {
  [Language.EN]: "Nabaha",
  [Language.AR]: "نباهة"
};

export const UI_TEXT = {
  [Language.EN]: {
    dashboard: "Live Dashboard",
    map: "Risk Map",
    analytics: "Analytics",
    alerts: "Alerts",
    activeVehicles: "Active Vehicles",
    riskScore: "Risk Score",
    speed: "Speed",
    driver: "Driver",
    analyze: "AI Analysis",
    simulating: "Live Simulation Active",
    incidentHistory: "Incident Timeline",
    totalMonitored: "Monitored Vehicles",
    avgNetworkRisk: "Avg Network Risk",
    alertHighRisk: "High Risk Alert",
    viewDetails: "View Details",
    analyzing: "Analyzing...",
    close: "Close",
    aiInsight: "Nabaha AI Insight",
    systemStatus: "System Status: Operational",
    connectAbsher: "Absher Integration Active",
    riskTrends: "Risk Trends (24h)",
    incidentSeverity: "Incident Severity Distribution",
    systemAvailability: "System Availability",
    systemLatency: "System Latency",
    criticalAlerts: "Critical Alerts",
    requiresAttention: "Requires attention",
    realTimeSync: "Real-time sync active",
    liveNow: "Live now",
    logged: "Logged",
    noAlerts: "No active alerts requiring attention.",
    exportReport: "Export Report",
    alertSource: "Alert Source",
    riskFactor: "Risk Factor",
    timestamp: "Timestamp",
    action: "Action",
    mapLegend: "Legend",
    safe: "Safe",
    critical: "Critical",
    moderate: "Moderate",
    assessment: "Assessment",
    locationContext: "Location Context",
    recommendations: "Recommendations",
    sources: "Sources",
    mapDescription: "Real-time geospatial risk tracking. High-risk vehicles pulse red. Click any vehicle for detailed AI analysis.",
    newVehicles: "+2 new in last hour"
  },
  [Language.AR]: {
    dashboard: "لوحة المتابعة الحية",
    map: "خريطة المخاطر",
    analytics: "التحليلات",
    alerts: "التنبيهات",
    activeVehicles: "المركبات النشطة",
    riskScore: "درجة المخاطرة",
    speed: "السرعة",
    driver: "السائق",
    analyze: "تحليل الذكاء الاصطناعي",
    simulating: "المحاكاة الحية نشطة",
    incidentHistory: "سجل الحوادث",
    totalMonitored: "المركبات المراقبة",
    avgNetworkRisk: "متوسط مخاطر الشبكة",
    alertHighRisk: "تنبيه عالي الخطورة",
    viewDetails: "عرض التفاصيل",
    analyzing: "جاري التحليل...",
    close: "إغلاق",
    aiInsight: "رؤية نباهة الذكية",
    systemStatus: "حالة النظام: تشغيلي",
    connectAbsher: "تم الربط مع أبشر",
    riskTrends: "مؤشرات المخاطر (٢٤ ساعة)",
    incidentSeverity: "توزيع خطورة الحوادث",
    systemAvailability: "جاهزية النظام",
    systemLatency: "سرعة الاستجابة",
    criticalAlerts: "تنبيهات حرجة",
    requiresAttention: "يتطلب الانتباه",
    realTimeSync: "المزاحمة الحية نشطة",
    liveNow: "مباشر",
    logged: "مسجل",
    noAlerts: "لا توجد تنبيهات نشطة تتطلب الانتباه.",
    exportReport: "تصدير التقرير",
    alertSource: "المصدر",
    riskFactor: "عامل الخطر",
    timestamp: "الوقت",
    action: "الإجراء",
    mapLegend: "مفتاح الخريطة",
    safe: "آمن",
    critical: "حرج",
    moderate: "متوسط",
    assessment: "التقييم",
    locationContext: "سياق الموقع",
    recommendations: "التوصيات",
    sources: "المصادر",
    mapDescription: "تتبع المخاطر الجغرافية في الوقت الفعلي. المركبات عالية الخطورة تومض باللون الأحمر. اضغط على أي مركبة للتحليل الذكي.",
    newVehicles: "+٢ مركبات جديدة في آخر ساعة"
  }
};